### ISSUE TITLE
Swagger spec warning

### ISSUE THREAD

**Issue by IvanGoncharov** [darklynx/request-baskets#5]
```
GET https://raw.githubusercontent.com/darklynx/request-baskets/master/doc/api-swagger.yaml
- code: EXTRA_REFERENCE_PROPERTIES
  message: 'Extra JSON Reference properties will be ignored: description'
  path:
    - definitions
    - Request
    - properties
    - headers
```
you can solve this by wrapping `$ref` with `allOf`.
```yaml
allOf:
  $ref: '#/...'
```
